name: Build and test

on:
  push:
    branches: [ main, ffm-poc ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up all JDKs
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          17
          18
          19
          20
        distribution: 'corretto'
    - name: Run tests
      run: ./gradlew test
    - name: Run tests
      run: ./gradlew test
      env:
        FORCE_WINDOWS_FALLBACK: '1'
      if: matrix.os == 'windows-latest'
